.TH welcome 1
.SH NAME
welcome \- prints out a nice welcome message with useful statistics
.SH SYNTAX
.B welcome
.SH DESCRIPTION
The
.PN welcome
command makes a graphic box over box and prints out the time, 
day, 
and system stats
.PP
.PN welcome
assumes that the file /etc/motd exists.
.SH SEE ALSO
/etc/motd
.SH AUTHOR
Jim King (pulsar) Lincoln-Sudbury Regional High '88.
