#
# Public Domain.  1996/10/24 - sms
#
#	@(#)Makefile	1.0 (2.11BSD GTE) 1996/10/24
#
CFLAGS=	 -O
SEPFLAG= -i
DESTDIR=
OBJS=

all:

clean:

depend:

install:
	install -c -o root -m 755 makewhatis.sh ${DESTDIR}/usr/sbin/makewhatis

lint:

tags:
