all:	test1
	@echo "Running tests.."
	@echo ""
	@echo ""
	@echo "Test #1..."
	@echo ""
	@echo "You should see your Unix username below:"
	./test1
	@echo ""
	@echo ""
	@echo "End of tests."


test1: test1.c
	$(CC) -o test1 test1.c

clean:
	rm -f test1 *~ core *.o \#*
