.TH PRMAIL 1
.UC
.SH NAME
prmail \- print out mail in the post office
.SH SYNOPSIS
.B prmail
[ user ... ]
.SH DESCRIPTION
.I Prmail
prints the mail which waits for you,
or the specified user,
in the post office.
The mail is not disturbed.
.SH FILES
.ta 2i
/usr/spool/mail/*	post office
.SH SEE ALSO
from(1), Mail(1), mail(1)
